apiVersion: v1
kind: Service
metadata:
  name: supergraph-service
  namespace: default
spec:
  selector:
    app: supergraph
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP