#controller:
#  ingressController:
#    env:
#      LOG_LEVEL: trace
#      dump_config: true
gateway:
  admin:
    http:
      enabled: true
  proxy:
    http:
      enabled: true
    tls:
      enabled: false
  manager:
#  ingressController:
#    env:
#      LOG_LEVEL: trace